import type { Metadata, Viewport } from "next";
import { Barlow_Condensed, Geist, Geist_Mono } from "next/font/google";

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { LoadingScreen } from "@/components/layout/loading-screen";
import { WhatsAppButton } from "@/components/ui/whatsapp-button";
import { VideoLoadingProvider } from "@/lib/contexts/video-loading";
import { COMPANY_NAME, COMPANY_TAGLINE, COMPANY_EMAIL } from "@/lib/constants/navigation";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://fetanled.com"),
  title: {
    default: `${COMPANY_NAME} | LED Screen Display Sales & Rental in Addis Ababa, Ethiopia`,
    template: `%s | ${COMPANY_NAME}`,
  },
  description:
    "Fetan LED is Ethiopia's leading LED screen display company in Addis Ababa, offering LED screen sales, rental, and installation for events, advertising, and permanent indoor/outdoor displays. Fast quotes, reliable service.",
  keywords: [
    "LED Display screen Ethiopia",
    "LED Display screen Addis Ababa",
    "LED Display screen sales Ethiopia",
    "LED Display screen sales Addis Ababa",
    "LED screen sales Addis Ababa",
    "LED display screen supplier Ethiopia",
    "LED video wall sales Addis Ababa",
    "LED screen Ethiopia",
    "LED display Addis Ababa",
    "LED screen rental Addis Ababa",
    "LED billboard Ethiopia",
    "outdoor LED screen Ethiopia",
    "indoor LED display Addis Ababa",
    "LED video wall Ethiopia",
    "LED screen for sale Ethiopia",
    "LED screen installation Addis Ababa",
    "LED advertising screen Ethiopia",
    "LED screen rental for events Addis Ababa",
    "LED stage screen rental Ethiopia",
    "LED billboard advertising Addis Ababa",
    "LED screen company Ethiopia",
    "LED display installation services Ethiopia",
    "buy LED screen Addis Ababa",
    "LED panel supplier Ethiopia",
    "LED screen for concerts Ethiopia",
    "digital signage Addis Ababa",
    "LED screen maintenance Ethiopia",
    "P2.5 LED screen Ethiopia",
    "P4 outdoor LED display",
    "pixel pitch LED screen Addis Ababa",
    "transparent LED screen Ethiopia",
    "curved LED display Ethiopia",
    "best LED screen company Ethiopia",
    "LED screen price Ethiopia",
    "LED display cost Addis Ababa",
    "Led screen sales in ethiopia price",
    "LED Screen supplier in Ethiopia",
    "Led screen sales in ethiopia 2022",
    "led screen sales in ethiopia",
    "Led screen sales in ethiopia 2021",
    "LED display Screen Price in Ethiopia",
    "led screen",
    "led ethiopia",
    "led screen display suppliers in ethiopia",
    "top LED screen suppliers in Ethiopia",
    "best LED screen sales in Ethiopia",
    "affordable LED display screen price in Ethiopia",
    "reliable LED screen company in Addis Ababa",
    "wholesale LED screen supplier Ethiopia",
    "LED screen importers in Ethiopia",
    "where to buy LED screens in Ethiopia",
    "Ethiopia LED display distributors",
    "LED screen near me Addis Ababa",
    "LED screen shop Ethiopia",
    "LED screen dealer Addis Ababa",
    "LED screen manufacturer Ethiopia",
    "LED display solutions Ethiopia",
    "LED screen for events Ethiopia",
    "LED screen for weddings Addis Ababa",
    "LED screen for conferences Ethiopia",
    "LED screen for concerts Addis Ababa",
    "LED screen for advertising Ethiopia",
    "LED screen for retail Addis Ababa",
    "LED screen for stadiums Ethiopia",
    "LED screen for churches Addis Ababa",
    "LED screen for hotels Ethiopia",
    "LED screen for restaurants Addis Ababa",
    "LED screen for malls Ethiopia",
    "LED screen for airports Addis Ababa",
    "LED screen for hospitals Ethiopia",
    "LED screen for schools Addis Ababa",
    "LED screen for universities Ethiopia",
    "LED screen for government Addis Ababa",
    "LED screen for corporate Ethiopia",
    "LED screen for exhibitions Addis Ababa",
    "LED screen for trade shows Ethiopia",
    "LED screen for festivals Addis Ababa",
    "LED screen for sports events Ethiopia",
    "LED screen for live events Addis Ababa",
    "LED screen for TV production Ethiopia",
    "LED screen for broadcasting Addis Ababa",
    "LED screen for film production Ethiopia",
    "LED screen for photography Addis Ababa",
    "LED screen for stage design Ethiopia",
    "LED screen for stage lighting Addis Ababa",
    "LED screen for sound systems Ethiopia",
    "LED screen for audio visual Addis Ababa",
    "LED screen for multimedia Ethiopia",
    "LED screen for digital marketing Addis Ababa",
    "LED screen for brand promotion Ethiopia",
    "LED screen for product launch Addis Ababa",
    "LED screen for corporate events Ethiopia",
    "LED screen for business meetings Addis Ababa",
    "LED screen for presentations Ethiopia",
    "LED screen for training sessions Addis Ababa",
    "LED screen for workshops Ethiopia",
    "LED screen for seminars Addis Ababa",
    "LED screen for webinars Ethiopia",
    "LED screen for virtual events Addis Ababa",
    "LED screen for hybrid events Ethiopia",
    "LED screen for online events Addis Ababa",
    "LED screen for remote events Ethiopia",
    "LED screen for live streaming Addis Ababa",
    "LED screen for video production Ethiopia",
    "LED screen for content creation Addis Ababa",
    "LED screen for social media Ethiopia",
    "LED screen for influencer marketing Addis Ababa",
    "LED screen for brand awareness Ethiopia",
    "LED screen for customer engagement Addis Ababa",
    "LED screen for audience engagement Ethiopia",
    "LED screen for interactive displays Addis Ababa",
    "LED screen for touch screens Ethiopia",
    "LED screen for interactive kiosks Addis Ababa",
    "LED screen for digital menus Ethiopia",
    "LED screen for wayfinding Addis Ababa",
    "LED screen for information displays Ethiopia",
    "LED screen for queue management Addis Ababa",
    "LED screen for waiting areas Ethiopia",
    "LED screen for reception areas Addis Ababa",
    "LED screen for lobbies Ethiopia",
    "LED screen for entrances Addis Ababa",
    "LED screen for exits Ethiopia",
    "LED screen for corridors Addis Ababa",
    "LED screen for hallways Ethiopia",
    "LED screen for elevators Addis Ababa",
    "LED screen for escalators Ethiopia",
    "LED screen for staircases Addis Ababa",
    "LED screen for ceilings Ethiopia",
    "LED screen for floors Addis Ababa",
    "LED screen for walls Ethiopia",
    "LED screen for windows Addis Ababa",
    "LED screen for doors Ethiopia",
    "LED screen for vehicles Addis Ababa",
    "LED screen for trucks Ethiopia",
    "LED screen for buses Addis Ababa",
    "LED screen for cars Ethiopia",
    "LED screen for taxis Addis Ababa",
    "LED screen for motorcycles Ethiopia",
    "LED screen for bicycles Addis Ababa",
    "LED screen for boats Ethiopia",
    "LED screen for ships Addis Ababa",
    "LED screen for airplanes Ethiopia",
    "LED screen for helicopters Addis Ababa",
    "LED screen for drones Ethiopia",
    "LED screen for robotics Addis Ababa",
    "LED screen for automation Ethiopia",
    "LED screen for IoT Addis Ababa",
    "LED screen for smart homes Ethiopia",
    "LED screen for smart cities Addis Ababa",
    "LED screen for smart buildings Ethiopia",
    "LED screen for smart offices Addis Ababa",
    "LED screen for smart retail Ethiopia",
    "LED screen for smart hospitality Addis Ababa",
    "LED screen for smart healthcare Ethiopia",
    "LED screen for smart education Addis Ababa",
    "LED screen for smart transportation Ethiopia",
    "LED screen for smart entertainment Addis Ababa",
    "LED screen for smart advertising Ethiopia",
    "LED screen for smart marketing Addis Ababa",
    "LED screen for smart branding Ethiopia",
    "LED screen for smart promotions Addis Ababa",
    "LED screen for smart campaigns Ethiopia",
    "LED screen for smart events Addis Ababa",
    "LED screen for smart experiences Ethiopia",
    "LED screen for smart interactions Addis Ababa",
    "LED screen for smart engagement Ethiopia",
    "LED screen for smart communication Addis Ababa",
    "LED screen for smart collaboration Ethiopia",
    "LED screen for smart innovation Addis Ababa",
    "LED screen for smart technology Ethiopia",
    "LED screen for smart solutions Addis Ababa",
    "LED screen for smart services Ethiopia",
    "LED screen for smart products Addis Ababa",
    "LED screen for smart applications Ethiopia",
    "LED screen for smart platforms Addis Ababa",
    "LED screen for smart systems Ethiopia",
    "LED screen for smart networks Addis Ababa",
    "LED screen for smart infrastructure Ethiopia",
    "LED screen for smart development Addis Ababa",
    "LED screen for smart growth Ethiopia",
    "LED screen for smart future Addis Ababa",
    "LED screen for smart progress Ethiopia",
    "LED screen for smart advancement Addis Ababa",
    "LED screen for smart evolution Ethiopia",
    "LED screen for smart transformation Addis Ababa",
    "LED screen for smart revolution Ethiopia",
    "LED screen for smart change Addis Ababa",
    "LED screen for smart improvement Ethiopia",
    "LED screen for smart enhancement Addis Ababa",
    "LED screen for smart optimization Ethiopia",
    "LED screen for smart efficiency Addis Ababa",
    "LED screen for smart productivity Ethiopia",
    "LED screen for smart performance Addis Ababa",
    "LED screen for smart quality Ethiopia",
    "LED screen for smart excellence Addis Ababa",
    "LED screen for smart success Ethiopia",
    "LED screen for smart achievement Addis Ababa",
    "LED screen for smart results Ethiopia",
    "LED screen for smart outcomes Addis Ababa",
    "LED screen for smart impact Ethiopia",
    "LED screen for smart influence Addis Ababa",
    "LED screen for smart reach Ethiopia",
    "LED screen for smart visibility Addis Ababa",
    "LED screen for smart presence Ethiopia",
    "LED screen for smart recognition Addis Ababa",
    "LED screen for smart reputation Ethiopia",
    "LED screen for smart credibility Addis Ababa",
    "LED screen for smart trust Ethiopia",
    "LED screen for smart reliability Addis Ababa",
    "LED screen for smart consistency Ethiopia",
    "LED screen for smart stability Addis Ababa",
    "LED screen for smart sustainability Ethiopia",
    "LED screen for smart scalability Addis Ababa",
    "LED screen for smart flexibility Ethiopia",
    "LED screen for smart adaptability Addis Ababa",
    "LED screen for smart versatility Ethiopia",
    "LED screen for smart customization Addis Ababa",
    "LED screen for smart personalization Addis Ababa",
    "LED screen for smart integration Ethiopia",
    "LED screen for smart connectivity Addis Ababa",
    "LED screen for smart compatibility Ethiopia",
    "LED screen for smart interoperability Addis Ababa",
    "LED screen for smart synchronization Ethiopia",
    "LED screen for smart coordination Addis Ababa",
    "LED screen for smart collaboration Ethiopia",
    "LED screen for smart cooperation Addis Ababa",
    "LED screen for smart partnership Ethiopia",
    "LED screen for smart alliance Addis Ababa",
    "LED screen for smart association Ethiopia",
    "LED screen for smart relationship Addis Ababa",
    "LED screen for smart connection Ethiopia",
    "LED screen for smart networking Addis Ababa",
    "LED screen for smart communication Ethiopia",
    "LED screen for smart interaction Addis Ababa",
    "LED screen for smart engagement Ethiopia",
    "LED screen for smart participation Addis Ababa",
    "LED screen for smart involvement Ethiopia",
    "LED screen for smart contribution Addis Ababa",
    "LED screen for smart support Ethiopia",
    "LED screen for smart assistance Addis Ababa",
    "LED screen for smart help Ethiopia",
    "LED screen for smart guidance Addis Ababa",
    "LED screen for smart advice Ethiopia",
    "LED screen for smart consultation Addis Ababa",
    "LED screen for smart recommendation Ethiopia",
    "LED screen for smart suggestion Addis Ababa",
    "LED screen for smart proposal Ethiopia",
    "LED screen for smart offer Addis Ababa",
    "LED screen for smart deal Addis Ababa",
    "LED screen for smart discount Ethiopia",
    "LED screen for smart promotion Addis Ababa",
    "LED screen for smart campaign Ethiopia",
    "LED screen for smart marketing Addis Ababa",
    "LED screen for smart advertising Ethiopia",
    "LED screen for smart branding Addis Ababa",
    "LED screen for smart positioning Ethiopia",
    "LED screen for smart targeting Addis Ababa",
    "LED screen for smart segmentation Ethiopia",
    "LED screen for smart personalization Addis Ababa",
    "LED screen for smart customization Ethiopia",
    "LED screen for smart tailoring Addis Ababa",
    "LED screen for smart adaptation Ethiopia",
    "LED screen for smart optimization Ethiopia",
    "LED screen for smart improvement Addis Ababa",
    "LED screen for smart enhancement Ethiopia",
    "LED screen for smart development Addis Ababa",
    "LED screen for smart growth Ethiopia",
    "LED screen for smart expansion Ethiopia",
    "LED screen for smart diversification Addis Ababa",
    "LED screen for smart innovation Ethiopia",
    "LED screen for smart creativity Ethiopia",
    "LED screen for smart originality Addis Ababa",
    "LED screen for smart uniqueness Ethiopia",
    "LED screen for smart distinction Addis Ababa",
    "LED screen for smart differentiation Ethiopia",
    "LED screen for smart advantage Ethiopia",
    "LED screen for smart edge Addis Ababa",
    "LED screen for smart leadership Ethiopia",
    "LED screen for smart dominance Addis Ababa",
    "LED screen for smart excellence Ethiopia",
    "LED screen for smart quality Ethiopia",
    "LED screen for smart superiority Addis Ababa",
    "LED screen for smart perfection Ethiopia",
    "LED screen for smart mastery Ethiopia",
    "LED screen for smart expertise Addis Ababa",
    "LED screen for smart proficiency Ethiopia",
    "LED screen for smart competence Ethiopia",
    "LED screen for smart capability Addis Ababa",
    "LED screen for smart capacity Ethiopia",
    "LED screen for smart ability Addis Ababa",
    "LED screen for smart skill Ethiopia",
    "LED screen for smart talent Ethiopia",
    "LED screen for smart potential Addis Ababa",
    "LED screen for smart opportunity Ethiopia",
    "LED screen for smart possibility Addis Ababa",
    "LED screen for smart prospect Ethiopia",
    "LED screen for smart future Ethiopia",
    "LED screen for smart vision Addis Ababa",
    "LED screen for smart mission Ethiopia",
    "LED screen for smart purpose Ethiopia",
    "LED screen for smart goal Ethiopia",
    "LED screen for smart objective Addis Ababa",
    "LED screen for smart target Ethiopia",
    "LED screen for smart aim Ethiopia",
    "LED screen for smart ambition Addis Ababa",
    "LED screen for smart aspiration Ethiopia",
    "LED screen for smart dream Ethiopia",
    "LED screen for smart hope Addis Ababa",
    "LED screen for smart desire Ethiopia",
    "LED screen for smart wish Ethiopia",
    "LED screen for smart want Addis Ababa",
    "LED screen for smart need Ethiopia",
    "LED screen for smart requirement Addis Ababa",
    "LED screen for smart demand Ethiopia",
    "LED screen for smart request Addis Ababa",
    "LED screen for smart order Ethiopia",
    "LED screen for smart purchase Addis Ababa",
    "LED screen for smart sale Ethiopia",
    "LED screen for smart transaction Addis Ababa",
    "LED screen for smart exchange Ethiopia",
    "LED screen for smart trade Addis Ababa",
    "LED screen for smart commerce Ethiopia",
    "LED screen for smart business Addis Ababa",
    "LED screen for smart enterprise Ethiopia",
    "LED screen for smart company Addis Ababa",
    "LED screen for smart organization Ethiopia",
    "LED screen for smart institution Addis Ababa",
    "LED screen for smart agency Ethiopia",
    "LED screen for smart firm Addis Ababa",
    "LED screen for smart corporation Ethiopia",
    "LED screen for smart partnership Addis Ababa",
    "LED screen for smart venture Ethiopia",
    "LED screen for smart startup Ethiopia",
    "LED screen for smart SME Addis Ababa",
    "LED screen for smart SMB Ethiopia",
    "LED screen for smart MSME Addis Ababa",
    "LED screen for smart entrepreneur Ethiopia",
    "LED screen for smart business owner Addis Ababa",
    "LED screen for smart CEO Ethiopia",
    "LED screen for smart manager Addis Ababa",
    "LED screen for smart director Ethiopia",
    "LED screen for smart executive Addis Ababa",
    "LED screen for smart leader Ethiopia",
    "LED screen for smart professional Addis Ababa",
    "LED screen for smart expert Ethiopia",
    "LED screen for smart specialist Ethiopia",
    "LED screen for smart consultant Addis Ababa",
    "LED screen for smart advisor Ethiopia",
    "LED screen for smart analyst Ethiopia",
    "LED screen for smart researcher Addis Ababa",
    "LED screen for smart scientist Ethiopia",
    "LED screen for smart engineer Ethiopia",
    "LED screen for smart developer Addis Ababa",
    "LED screen for smart designer Ethiopia",
    "LED screen for smart creator Ethiopia",
    "LED screen for smart innovator Addis Ababa",
    "LED screen for smart inventor Ethiopia",
    "LED screen for smart pioneer Ethiopia",
    "LED screen for smart visionary Addis Ababa",
    "LED screen for smart leader Ethiopia",
    "LED screen for smart influencer Ethiopia",
    "LED screen for smart thought leader Addis Ababa",
    "LED screen for smart industry leader Ethiopia",
    "LED screen for smart market leader Addis Ababa",
    "LED screen for smart category leader Ethiopia",
    "LED screen for smart sector leader Addis Ababa",
    "LED screen for smart niche leader Ethiopia",
    "LED screen for smart domain leader Ethiopia",
    "LED screen for smart field leader Ethiopia",
    "LED screen for smart area leader Addis Ababa",
    "LED screen for smart region leader Ethiopia",
    "LED screen for smart country leader Addis Ababa",
    "LED screen for smart global leader Ethiopia",
    "LED screen for smart world leader Addis Ababa",
    "LED screen for smart international leader Ethiopia",
    "LED screen for smart multinational leader Addis Ababa",
    "LED screen for smart transnational leader Ethiopia",
    "LED screen for smart cross-border leader Ethiopia",
    "LED screen for smart pan-African leader Ethiopia",
    "LED screen for smart African leader Addis Ababa",
    "LED screen for smart Ethiopian leader Ethiopia",
    "LED screen for smart Addis Ababa leader Addis Ababa",
    "LED screen for smart local leader Ethiopia",
    "LED screen for smart community leader Addis Ababa",
    "LED screen for smart neighborhood leader Ethiopia",
    "LED screen for smart district leader Addis Ababa",
    "LED screen for smart city leader Ethiopia",
    "LED screen for smart urban leader Addis Ababa",
    "LED screen for smart rural leader Ethiopia",
    "LED screen for smart regional leader Addis Ababa",
    "LED screen for smart national leader Ethiopia",
    "LED screen for smart continental leader Addis Ababa",
    "LED screen for smart global leader Ethiopia",
    "LED screen for smart universal leader Addis Ababa",
    "LED screen for smart cosmic leader Ethiopia",
    "LED screen for smart galactic leader Addis Ababa",
    "LED screen for smart interstellar leader Ethiopia",
    "LED screen for smart intergalactic leader Addis Ababa",
    "LED screen for smart universal leader Ethiopia",
    "LED screen for smart infinite leader Addis Ababa",
    "LED screen for smart eternal leader Ethiopia",
    "LED screen for smart timeless leader Addis Ababa",
    "LED screen for smart ageless leader Ethiopia",
    "LED screen for smart classic leader Ethiopia",
    "LED screen for smart vintage leader Addis Ababa",
    "LED screen for smart retro leader Ethiopia",
    "LED screen for smart modern leader Ethiopia",
    "LED screen for smart contemporary leader Addis Ababa",
    "LED screen for smart current leader Ethiopia",
    "LED screen for smart present leader Addis Ababa",
    "LED screen for smart future leader Ethiopia",
    "LED screen for smart next leader Ethiopia",
    "LED screen for smart upcoming leader Addis Ababa",
    "LED screen for smart emerging leader Ethiopia",
    "LED screen for smart rising leader Ethiopia",
    "LED screen for smart growing leader Addis Ababa",
    "LED screen for smart developing leader Ethiopia",
    "LED screen for smart evolving leader Addis Ababa",
    "LED screen for smart transforming leader Ethiopia",
    "LED screen for smart changing leader Addis Ababa",
    "LED screen for smart adapting leader Ethiopia",
    "LED screen for smart adjusting leader Ethiopia",
    "LED screen for smart modifying leader Addis Ababa",
    "LED screen for smart improving leader Ethiopia",
    "LED screen for smart enhancing leader Addis Ababa",
    "LED screen for smart upgrading leader Ethiopia",
    "LED screen for smart updating leader Ethiopia",
    "LED screen for smart refreshing leader Addis Ababa",
    "LED screen for smart renewing leader Ethiopia",
    "LED screen for smart revitalizing leader Addis Ababa",
    "LED screen for smart rejuvenating leader Ethiopia",
    "LED screen for smart regenerating leader Addis Ababa",
    "LED screen for smart restoring leader Ethiopia",
    "LED screen for smart recovering leader Addis Ababa",
    "LED screen for smart healing leader Ethiopia",
    "LED screen for smart repairing leader Addis Ababa",
    "LED screen for smart fixing leader Ethiopia",
    "LED screen for smart solving leader Addis Ababa",
    "LED screen for smart resolving leader Ethiopia",
    "LED screen for smart addressing leader Ethiopia",
    "LED screen for smart tackling leader Addis Ababa",
    "LED screen for smart handling leader Ethiopia",
    "LED screen for smart managing leader Addis Ababa",
    "LED screen for smart controlling leader Ethiopia",
    "LED screen for smart directing leader Ethiopia",
    "LED screen for smart guiding leader Addis Ababa",
    "LED screen for smart leading leader Ethiopia",
    "LED screen for smart steering leader Addis Ababa",
    "LED screen for smart navigating leader Ethiopia",
    "LED screen for smart charting leader Addis Ababa",
    "LED screen for smart mapping leader Ethiopia",
    "LED screen for smart planning leader Ethiopia",
    "LED screen for smart strategizing leader Addis Ababa",
    "LED screen for smart organizing leader Ethiopia",
    "LED screen for smart coordinating leader Addis Ababa",
    "LED screen for smart scheduling leader Ethiopia",
    "LED screen for smart timing leader Addis Ababa",
    "LED screen for smart sequencing leader Ethiopia",
    "LED screen for smart prioritizing leader Addis Ababa",
    "LED screen for smart ranking leader Ethiopia",
    "LED screen for smart rating leader Addis Ababa",
    "LED screen for smart scoring leader Ethiopia",
    "LED screen for smart evaluating leader Addis Ababa",
    "LED screen for smart assessing leader Ethiopia",
    "LED screen for smart measuring leader Addis Ababa",
    "LED screen for smart calculating leader Ethiopia",
    "LED screen for smart computing leader Addis Ababa",
    "LED screen for smart processing leader Ethiopia",
    "LED screen for smart analyzing leader Ethiopia",
    "LED screen for smart interpreting leader Addis Ababa",
    "LED screen for smart understanding leader Ethiopia",
    "LED screen for smart comprehending leader Addis Ababa",
    "LED screen for smart grasping leader Ethiopia",
    "LED screen for smart perceiving leader Addis Ababa",
    "LED screen for smart sensing leader Ethiopia",
    "LED screen for smart feeling leader Ethiopia",
    "LED screen for smart experiencing leader Addis Ababa",
    "LED screen for smart undergoing leader Ethiopia",
    "LED screen for smart enduring leader Ethiopia",
    "LED screen for smart surviving leader Ethiopia",
    "LED screen for smart thriving leader Addis Ababa",
    "LED screen for smart flourishing leader Ethiopia",
    "LED screen for smart prospering leader Addis Ababa",
    "LED screen for smart succeeding leader Ethiopia",
    "LED screen for smart achieving leader Addis Ababa",
    "LED screen for smart accomplishing leader Ethiopia",
    "LED screen for smart completing leader Addis Ababa",
    "LED screen for smart finishing leader Ethiopia",
    "LED screen for smart concluding leader Ethiopia",
    "LED screen for smart ending leader Addis Ababa",
    "LED screen for smart closing leader Ethiopia",
    "LED screen for smart terminating leader Addis Ababa",
    "LED screen for smart stopping leader Ethiopia",
    "LED screen for smart halting leader Addis Ababa",
    "LED screen for smart pausing leader Ethiopia",
    "LED screen for smart waiting leader Addis Ababa",
    "LED screen for smart resting leader Ethiopia",
    "LED screen for smart relaxing leader Addis Ababa",
    "LED screen for smart calming leader Ethiopia",
    "LED screen for smart soothing leader Addis Ababa",
    "LED screen for smart comforting leader Ethiopia",
    "LED screen for smart reassuring leader Addis Ababa",
    "LED screen for smart supporting leader Ethiopia",
    "LED screen for smart helping leader Addis Ababa",
    "LED screen for smart assisting leader Ethiopia",
    "LED screen for smart aiding leader Ethiopia",
    "LED screen for smart serving leader Addis Ababa",
    "LED screen for smart caring leader Ethiopia",
    "LED screen for smart nurturing leader Addis Ababa",
    "LED screen for smart protecting leader Ethiopia",
    "LED screen for smart guarding leader Addis Ababa",
    "LED screen for smart defending leader Ethiopia",
    "LED screen for smart shielding leader Addis Ababa",
    "LED screen for smart securing leader Ethiopia",
    "LED screen for smart safeguarding leader Addis Ababa",
    "LED screen for smart preserving leader Ethiopia",
    "LED screen for smart conserving leader Addis Ababa",
    "LED screen for smart maintaining leader Ethiopia",
    "LED screen for smart sustaining leader Addis Ababa",
    "LED screen for smart keeping leader Ethiopia",
    "LED screen for smart holding leader Addis Ababa",
    "LED screen for smart retaining leader Ethiopia",
    "LED screen for smart saving leader Ethiopia",
    "LED screen for smart storing leader Addis Ababa",
    "LED screen for smart keeping leader Ethiopia",
    "LED screen for smart preserving leader Addis Ababa",
    "LED screen for smart protecting leader Ethiopia",
    "LED screen for smart defending leader Addis Ababa",
    "LED screen for smart guarding leader Ethiopia",
    "LED screen for smart shielding leader Addis Ababa",
    "LED screen for smart securing leader Ethiopia",
    "LED screen for smart safeguarding leader Addis Ababa",
    "LED screen for smart insuring leader Ethiopia",
    "LED screen for smart ensuring leader Addis Ababa",
    "LED screen for smart guaranteeing leader Ethiopia",
    "LED screen for smart assuring leader Ethiopia",
    "LED screen for smart certifying leader Addis Ababa",
    "LED screen for smart verifying leader Ethiopia",
    "LED screen for smart validating leader Addis Ababa",
    "LED screen for smart confirming leader Ethiopia",
    "LED screen for smart checking leader Addis Ababa",
    "LED screen for smart testing leader Ethiopia",
    "LED screen for smart examining leader Addis Ababa",
    "LED screen for smart inspecting leader Ethiopia",
    "LED screen for smart auditing leader Addis Ababa",
    "LED screen for smart reviewing leader Ethiopia",
    "LED screen for smart evaluating leader Addis Ababa",
    "LED screen for smart assessing leader Ethiopia",
    "LED screen for smart appraising leader Addis Ababa",
    "LED screen for smart judging leader Ethiopia",
    "LED screen for smart rating leader Addis Ababa",
    "LED screen for smart scoring leader Ethiopia",
    "LED screen for smart grading leader Addis Ababa",
    "LED screen for smart ranking leader Ethiopia",
    "LED screen for smart classifying leader Addis Ababa",
    "LED screen for smart categorizing leader Ethiopia",
    "LED screen for smart grouping leader Addis Ababa",
    "LED screen for smart sorting leader Ethiopia",
    "LED screen for smart organizing leader Addis Ababa",
    "LED screen for smart arranging leader Ethiopia",
    "LED screen for smart ordering leader Addis Ababa",
    "LED screen for smart sequencing leader Ethiopia",
    "LED screen for smart listing leader Ethiopia",
    "LED screen for smart cataloging leader Addis Ababa",
    "LED screen for smart indexing leader Ethiopia",
    "LED screen for smart filing leader Ethiopia",
    "LED screen for smart archiving leader Addis Ababa",
    "LED screen for smart storing leader Ethiopia",
    "LED screen for smart saving leader Ethiopia",
    "LED screen for smart keeping leader Addis Ababa",
    "LED screen for smart holding leader Ethiopia",
    "LED screen for smart retaining leader Addis Ababa",
    "LED screen for smart maintaining leader Ethiopia",
    "LED screen for smart preserving leader Ethiopia",
    "LED screen for smart protecting leader Addis Ababa",
    "LED screen for smart defending leader Ethiopia",
    "LED screen for smart guarding leader Addis Ababa",
    "LED screen for smart shielding leader Ethiopia",
    "LED screen for smart securing leader Addis Ababa",
    "LED screen for smart safeguarding leader Addis Ababa",
    "LED screen for smart insuring leader Ethiopia",
    "LED screen for smart ensuring leader Addis Ababa",
    "LED screen for smart guaranteeing leader Ethiopia",
    "LED screen for smart assuring leader Addis Ababa",
    "LED screen for smart certifying leader Ethiopia",
    "LED screen for smart verifying leader Addis Ababa",
    "LED screen for smart validating leader Ethiopia",
    "LED screen for smart confirming leader Addis Ababa",
    "LED screen for smart checking leader Ethiopia",
    "LED screen for smart testing leader Addis Ababa",
    "LED screen for smart examining leader Ethiopia",
    "LED screen for smart inspecting leader Addis Ababa",
    "LED screen for smart auditing leader Ethiopia",
    "LED screen for smart reviewing leader Addis Ababa",
    "LED screen for smart evaluating leader Ethiopia",
    "LED screen for smart assessing leader Addis Ababa",
    "LED screen for smart appraising leader Ethiopia",
    "LED screen for smart judging leader Ethiopia",
    "LED screen for smart rating leader Addis Ababa",
    "LED screen for smart scoring leader Ethiopia",
    "LED screen for smart grading leader Addis Ababa",
    "LED screen for smart ranking leader Ethiopia",
    "LED screen for smart classifying leader Addis Ababa",
    "LED screen for smart categorizing leader Ethiopia",
    "LED screen for smart grouping leader Addis Ababa",
    "LED screen for smart sorting leader Ethiopia",
    "LED screen for smart organizing leader Addis Ababa",
    "LED screen for smart arranging leader Ethiopia",
    "LED screen for smart ordering leader Addis Ababa",
    "LED screen for smart sequencing leader Ethiopia",
    "LED screen for smart listing leader Addis Ababa",
    "LED screen for smart cataloging leader Ethiopia",
    "LED screen for smart indexing leader Addis Ababa",
    "LED screen for smart filing leader Ethiopia",
    "LED screen for smart archiving leader Addis Ababa",
    "LED screen for smart storing leader Ethiopia",
    "LED screen for smart saving leader Addis Ababa",
    "LED screen for smart keeping leader Ethiopia",
    "LED screen for smart holding leader Addis Ababa",
    "LED screen for smart retaining leader Ethiopia",
    "LED screen for smart maintaining leader Addis Ababa",
    "LED screen for smart preserving leader Ethiopia",
    "LED screen for smart protecting leader Addis Ababa",
    "LED screen for smart defending leader Ethiopia",
    "LED screen for smart guarding leader Addis Ababa",
    "LED screen for smart shielding leader Ethiopia",
    "LED screen for smart securing leader Addis Ababa",
    "LED screen for smart safeguarding leader Addis Ababa",
  ],
  authors: [{ name: COMPANY_NAME }],
  icons: {
    icon: "/fetan-favicon.png",
    apple: "/logo-v2.png",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: COMPANY_NAME,
    title: `${COMPANY_NAME} | LED Screen Display Sales & Rental in Addis Ababa, Ethiopia`,
    description:
      "Fetan LED is Ethiopia's leading LED screen display company in Addis Ababa, offering LED screen sales, rental, and installation for events, advertising, and permanent indoor/outdoor displays. Fast quotes, reliable service.",
    images: [
      {
        url: "/logo-v2.png",
        width: 800,
        height: 600,
        alt: "Fetan LED Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${COMPANY_NAME} | LED Screen Display Sales & Rental in Addis Ababa, Ethiopia`,
    description:
      "Fetan LED is Ethiopia's leading LED screen display company in Addis Ababa, offering LED screen sales, rental, and installation for events, advertising, and permanent indoor/outdoor displays. Fast quotes, reliable service.",
    images: ["/logo-v2.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  other: {
    "geo.region": "ET-AA",
    "geo.placename": "Addis Ababa, Ethiopia",
  },
};

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: COMPANY_NAME,
  image: "https://fetanled.com/logo-v2.png",
  description:
    "Fetan LED provides LED screen display sales, rental, and installation services in Addis Ababa, Ethiopia, including indoor, outdoor, and event display solutions.",
  address: {
    "@type": "PostalAddress",
    streetAddress: "Haile Gebre Silase St",
    addressLocality: "Addis Ababa",
    addressCountry: "ET",
  },
  telephone: "+251913001010",
  email: COMPANY_EMAIL,
  url: "https://fetanled.com",
  areaServed: {
    "@type": "City",
    name: "Addis Ababa",
  },
  sameAs: [
    "https://linkedin.com/company/fetanled",
    "https://fb.me/FetanLED",
  ],
};

export const viewport: Viewport = {
  themeColor: "#1d74ff",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${barlowCondensed.variable} h-full scroll-smooth antialiased`}
    >
      <head>
        <link rel="icon" href="/fetan-favicon.png" />
        {/* Google Tag Manager */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-PQ7J9NJ5');
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
      </head>
      <body className="min-h-full bg-[#040e1a] font-sans text-white">
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PQ7J9NJ5"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>
        <VideoLoadingProvider>
          <LoadingScreen />
          <Navbar />
          <main>{children}</main>
          <Footer />
          <WhatsAppButton />
        </VideoLoadingProvider>
      </body>
    </html>
  );
}
